### ISSUE TITLE
The training cost

### ISSUE THREAD

**Issue by leyangjin** [ActiveVisionLab/gaussctrl#1]
Hi, nice work! 
Just curious about the type and number of GPU used for training, and the time needed for the original training phase.

**Comment by jingwu2121** [comment]
Hi, the entire editing process is an inference process, it doesn't involve any training, the only training here is the 3DGS training. As we said in the README file, we use an NVIDIA RTX A5000 GPU (24G) for training (editing and train 3DGS). To fit a smaller GPU, you can also decrease the batch size and the number of reference frames, it should also work. Our batch size is 3, with 4 reference frames. So the entire training time is around 9mins if we edit 40 images, (which is a number that you can set in the hyperparameter, as introduced in the README file.) You can also decrease this number to speed up, should also work fine

**Comment by leyangjin** [comment]
Hi, thank you so much for your help!
