### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by yyhyyhyyhyyh** [ActiveVisionLab/gaussctrl#11]
Hi!I meet a problem.

[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
Disabled comet/tensorboard/wandb event writers
Printing profiling stats, from longest to shortest duration in seconds
GaussCtrlTrainer.train_iteration: 0.0805              
Traceback (most recent call last):
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 201, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 275, in train_iteration
    self.grad_scaler.scale(loss).backward()  # type: ignore
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
TypeError: backward() takes 2 positional arguments but 3 were given

So I want to ask if this has anything to do with the version issue?Thank you!

**Comment by yyhyyhyyhyyh** [comment]
and I want to ask you torch version.Thank you!

**Comment by jingwu2121** [comment]
We are using torch 2.1.2, see [here](https://docs.nerf.studio/quickstart/installation.html)

```
pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
```

**Comment by yyhyyhyyhyyh** [comment]
We are the same version, do you know what the error above is and why there is an extra parameter

**Comment by jingwu2121** [comment]
Are you able to perform the 2D editing? What are you trying to run, can you share the command?

**Comment by yyhyyhyyhyyh** [comment]
This error occurred after generating the view done editing.The command is:
ns-train gaussctrl --load-checkpoint output/bear/splatfacto/2024-09-07_140514/nerfstudio_models/step-000029999.ckpt --experiment-name bear --output-dir editbear --pipeline.datamanager.data data/bear --pipeline.prompt "a photo of a golden bear statue in the forest" --pipeline.guidance_scale 5 --pipeline.chunk_size 1 --pipeline.langsam_obj 'bear'

**Comment by yyhyyhyyhyyh** [comment]
train 3DGS is successful.This error occurred Edit model

**Comment by jingwu2121** [comment]
If I understand correctly, you have no problem running the code until [here](https://github.com/ActiveVisionLab/gaussctrl/blob/main/gaussctrl/gc_pipeline.py?plain=1#L277)?

**Comment by yyhyyhyyhyyh** [comment]
Sorry,I am unable to debug on the server,but I think maybe the key is:
File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 201, in train
loss, loss_dict, metrics_dict = self.train_iteration(step)
The complete shell for this section is as follows：
Start Editing: 
Reference views are [5, 12, 30, 32]
#############################
Generating view: [0]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:21<00:00,  1.07s/it]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [1]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [2]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [3]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [4]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [5]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [6]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [7]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [8]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [9]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [10]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [11]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [12]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [13]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [14]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [15]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [16]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [17]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [18]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [19]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [20]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [21]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [22]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [23]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [24]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [25]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [26]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [27]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [28]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [29]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [30]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [31]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [32]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [33]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [34]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [35]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [36]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [37]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [38]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
Generating view: [39]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
#############################
Done Editing
#############################
╭─────────────── viser ───────────────╮
│             ╷                       │
│   HTTP      │ http://0.0.0.0:7007   │
│   Websocket │ ws://0.0.0.0:7007     │
│             ╵                       │
╰─────────────────────────────────────╯
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
Disabled comet/tensorboard/wandb event writers
Printing profiling stats, from longest to shortest duration in seconds
GaussCtrlTrainer.train_iteration: 0.0805              
Traceback (most recent call last):
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 201, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 275, in train_iteration
    self.grad_scaler.scale(loss).backward()  # type: ignore
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
TypeError: backward() takes 2 positional arguments but 3 were given

**Comment by yyhyyhyyhyyh** [comment]
Maybe something wrong at return user_fn(self, *args) the *args
but when I print *args,I just see some tensors

**Comment by jingwu2121** [comment]
Hi there, can you try these two things?
- Comment out these [lines](https://github.com/ActiveVisionLab/gaussctrl/blob/main/gaussctrl/gc_trainer.py?plain=1#L76-L78), so what it does is that it doesn't perform 2D editing anymore, you just use your unedited images to continue the splat training. Have a look at if using original images to train splat works
- If it works then, the problem might be the edited images. Here you didn't successfully edit the images, since all the images you got were black. You might want to visualize those edited images. see this [line](https://github.com/ActiveVisionLab/gaussctrl/blob/main/gaussctrl/gc_pipeline.py?plain=1#L216). 
  - A few things to try are: 
    - removing the NFSW detected in diffusers 
    - trying another seed/prompt and make sure you have correct edited images first
> Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.

**Comment by yyhyyhyyhyyh** [comment]
ok,I will have a try

**Comment by yyhyyhyyhyyh** [comment]
I comment out these lines you marked,but meet the same problem.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  7.57it/s]
Done loading Nerfstudio checkpoint from output/bear/splatfacto/2024-09-07_140514/nerfstudio_models/step-000029999.ckpt
╭─────────────── viser ───────────────╮
│             ╷                       │
│   HTTP      │ http://0.0.0.0:7007   │
│   Websocket │ ws://0.0.0.0:7007     │
│             ╵                       │
╰─────────────────────────────────────╯
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
Disabled comet/tensorboard/wandb event writers
(viser) Connection opened (0, 1 total), 469 persistent messages
Printing profiling stats, from longest to shortest duration in seconds
GaussCtrlTrainer.train_iteration: 69.1761             
Traceback (most recent call last):
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 201, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 275, in train_iteration
    self.grad_scaler.scale(loss).backward()  # type: ignore
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
TypeError: backward() takes 2 positional arguments but 3 were given
terminate called without an active exception
Aborted (core dumped)

**Comment by jingwu2121** [comment]
Hi there, also have a look at [this](https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/71). They are getting the same error as yours

**Comment by yyhyyhyyhyyh** [comment]
Thank you!I will have a look

**Comment by yyhyyhyyhyyh** [comment]
Hi!I seem to have noticed a problem.I printed the type of loss after this line of code:
loss = functools.reduce(torch.add, loss_dict.values())
But the loss is tensor,is it right?I think loss should be a scalar.Can you check it again?
Thank you very much!

**Comment by Kelvar00** [comment]
Is there a way to solve the problem? I encounter the exact problem

**Comment by Wangkkklll** [comment]
I have a similar problem, is there a solution?

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.54it/s]
Done Resetting Attention Processor
#############################
Start Editing: 
Reference views are [5, 12, 30, 32]
#############################
Generating view: [0, 1, 2]
  0%|                                                                                                                                                                                                                                           | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/wkl/anaconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/wkl/code/3d_edit/gaussctrl/gaussctrl/gc_trainer.py", line 78, in setup
    self.pipeline.edit_images()
  File "/home/wkl/code/3d_edit/gaussctrl/gaussctrl/gc_pipeline.py", line 209, in edit_images
    chunk_edited = self.pipe(
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet.py", line 1279, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/diffusers/models/controlnets/controlnet.py", line 808, in forward
    sample, res_samples = downsample_block(
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1334, in forward
    hidden_states = attn(
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/diffusers/models/transformers/transformer_2d.py", line 442, in forward
    hidden_states = block(
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/diffusers/models/attention.py", line 514, in forward
    attn_output = self.attn1(
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 588, in forward
    return self.processor(
  File "/home/wkl/code/3d_edit/gaussctrl/gaussctrl/utils.py", line 74, in __call__
    query = attn.to_q(hidden_states, *args)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wkl/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
