### ISSUE TITLE
Train data shuffle

### ISSUE THREAD

**Issue by massyzs** [ActiveVisionLab/gaussctrl#12]
Hi, thanks for your excellent work. 
May I ask how you changed the training data order? It seems that, for scene "bear", the image_idx is not as order in data folder. For example,  I want 9.png in the folder, but when I output data by select image_idx=9, the image is not what I want. It seems to be shuffled somewhere but I cannot found.

Would you kindly share your thoughts?

**Comment by jingwu2121** [comment]
Hi, in our experiments, we didn't use all the images for training, which might lead to your problem. You might want to look at this piece of code: https://github.com/ActiveVisionLab/gaussctrl/blob/main/gaussctrl/gc_datamanager.py?plain=1#L107-L109
