### ISSUE TITLE
inversion with edited prompt

### ISSUE THREAD

**Issue by yeobinhong** [ActiveVisionLab/gaussctrl#13]
the code here (line 138 in gc_pipeline.py) seems to invert the original image to latents zT using edited prompts (p hat in the paper). As self.positive_prompt is an edited prompt, e.g. 'a photo of a polar bear in the forest, best quality, extremely detailed'.

`            latent, _ = self.pipe(prompt=self.positive_prompt, #  placeholder here, since cfg=0
                                num_inference_steps=self.num_inference_steps, 
                                latents=init_latent, 
                                image=disparity, return_dict=False, guidance_scale=0, output_type='latent')
`

**Comment by jingwu2121** [comment]
Hi, there, as I suggested in the code comment. Empirically, the prompt is just a placeholder here, and the classifier free guidance is set to 0. Prompt doesn't have much effect on the inversion. Using the original prompt to invert is also possible.

**Comment by jingwu2121** [comment]
Hi, the bug is now fixed
