### ISSUE TITLE
Version Issues

### ISSUE THREAD

**Issue by yyhyyhyyhyyh** [ActiveVisionLab/gaussctrl#14]
Sorry,I still can't solve the backward problem that occurred before,I may need to check the version issue
Can you give me your conda list?
Thank you!

**Comment by jingwu2121** [comment]
[requirements.txt](https://github.com/user-attachments/files/17174101/requirements.txt)
Hi, there, this is my environment. :)

**Comment by yyhyyhyyhyyh** [comment]
When I pip install gsplat==0.1.3,This line will appear:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nerfstudio 1.0.0 requires gsplat==0.1.2.1, but you have gsplat 0.1.3 which is incompatible.
**Successfully installed gsplat-0.1.3**
But it seems that gsplat==0.1.3 is successfully installed,will this error have any impact?

**Comment by jingwu2121** [comment]
Hi, might need to have a try at different versions to see if gsplat version affects

**Comment by yyhyyhyyhyyh** [comment]
Thank you very much for your help, I have successfully run the program.This is excellent work.
I have another question. After I finish editing, there is a training process. What is this training for?

**Comment by yyhyyhyyhyyh** [comment]
By the way,nerfstudio==1.0.1 and gsplat==0.1.3 are compatible with all packages,and no code modification #2 (https://github.com/ActiveVisionLab/gaussctrl/pull/2)) is required

**Comment by jingwu2121** [comment]
The training is there to edit the splats, as introduced in our paper
