### ISSUE TITLE
ns-train gaussctrl problem about nerfstudio

### ISSUE THREAD

**Issue by ZhaoLongjiea** [ActiveVisionLab/gaussctrl#17]
my nerfstudio=1.1.4
after I finish this command： ns-train splatfacto --output-dir output --experiment-name bear --viewer.quit-on-train-completion True nerfstudio-data --data data/bear

Then I implement this command: 
ns-train gaussctrl --load-checkpoint output/bear/splatfacto/2024-10-24_170937/nerfstudio_models/step-000029999.ckpt --experiment-name bear --output-dir output/bear --pipeline.datamanager.data data/bear --pipeline.edit_prompt "a photo of a polar bear in the forest" --pipeline.reverse_prompt "a photo of a bear statue in the forest" --pipeline.guidance_scale 5 --pipeline.chunk_size 3 --pipeline.langsam_obj 'bear' --viewer.quit-on-train-completion True 

It is really weird that nerfstudio doesn't define the gaussctrl:
invalid choice: 'gaussctrl' (choose from           │
│ 'depth-nerfacto', 'dnerf', 'generfacto', 'instant-ngp', 'instant-ngp-bounded', 'mipnerf', 'nerfacto', 'nerfacto-big', 'nerfacto-huge',     │
│ 'neus', 'neus-facto', 'phototourism', 'semantic-nerfw', 'splatfacto', 'splatfacto-big', 'te
![1](https://github.com/user-attachments/assets/c40eb1f0-0c1c-4a66-a8ee-05d6d25a78d3)

**Comment by JiawangBian** [comment]
You didn't correctly install it. 

please try "pip install -e ." and verify your install "ns-train -h"
