### ISSUE TITLE
diffusers version issue

### ISSUE THREAD

**Issue by SydneyWarrenZhao** [ActiveVisionLab/gaussctrl#18]
python=3.10.15
CUDA11.8
When diffusers==0.26.0,I use this command "ns-train -h"
then
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/huggingface_hub/__init__.py)

I thought this is a mistake about diffusers version, then I upgrade the diffusers==0.31.0, then:

gaussctrl) lzha0538@gpu1-3w-1:~/3Dediting/gaussctrl$ ns-train -h
/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/nerfstudio/field_components/activations.py:32: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)
/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/nerfstudio/field_components/activations.py:39: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, g):
Traceback (most recent call last):
  File "/home/lzha0538/miniconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 263, in entrypoint
    tyro.cli(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_cli.py", line 207, in cli
    output = _cli_impl(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_cli.py", line 408, in _cli_impl
    parser_spec = _parsers.ParserSpecification.from_callable_or_type(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 114, in from_callable_or_type
    field_out = handle_field(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 320, in handle_field
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 526, in from_field
    subparser = ParserSpecification.from_callable_or_type(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 114, in from_callable_or_type
    field_out = handle_field(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 345, in handle_field
    return ParserSpecification.from_callable_or_type(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 114, in from_callable_or_type
    field_out = handle_field(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 345, in handle_field
    return ParserSpecification.from_callable_or_type(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 114, in from_callable_or_type
    field_out = handle_field(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 320, in handle_field
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/tyro/_parsers.py", line 469, in from_field
    assert default_name is not None, (

AssertionError: `pipeline.datamanager.dataparser` was provided a default value of type <class 'gaussctrl.gc_dataparser_ns.GaussCtrlDataParserConfig'> but no matching subcommand was found. A type may be missing in the Union type declaration for `pipeline.datamanager.dataparser`, which currently expects [typing.Annotated[nerfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig, _SubcommandConfiguration(name='nerfstudio-data', default=NerfstudioDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.Nerfstudio'>, data=PosixPath('.'), scale_factor=1.0, downscale_factor=None, scene_scale=1.0, orientation_method='up', center_method='poses', auto_scale_poses=True, eval_mode='fraction', train_split_fraction=0.9, eval_interval=8, depth_unit_scale_factor=0.001, load_3D_points=False), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParserConfig, _SubcommandConfiguration(name='minimal-parser', default=MinimalDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParser'>, data=PosixPath('/home/nikhil/nerfstudio-main/tests/data/lego_test/minimal_parser')), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenesDataParserConfig, _SubcommandConfiguration(name='arkit-data', default=ARKitScenesDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenes'>, data=PosixPath('data/ARKitScenes/3dod/Validation/41069021'), scale_factor=1.0, scene_scale=1.0, center_method='poses', auto_scale_poses=True, train_split_fraction=0.9, depth_unit_scale_factor=0.001), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.blender_dataparser.BlenderDataParserConfig, _SubcommandConfiguration(name='blender-data', default=BlenderDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.blender_dataparser.Blender'>, data=PosixPath('data/blender/lego'), scale_factor=1.0, alpha_color='white'), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGPDataParserConfig, _SubcommandConfiguration(name='instant-ngp-data', default=InstantNGPDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGP'>, data=PosixPath('data/ours/posterv2'), scene_scale=0.3333, eval_mode='fraction', train_split_fraction=0.9, eval_interval=8), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenesDataParserConfig, _SubcommandConfiguration(name='nuscenes-data', default=NuScenesDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenes'>, data=PosixPath('scene-0103'), data_dir=PosixPath('/mnt/local/NuScenes'), version='v1.0-mini', cameras=('FRONT',), mask_dir=None, train_split_fraction=0.9, verbose=False), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.dnerf_dataparser.DNeRFDataParserConfig, _SubcommandConfiguration(name='dnerf-data', default=DNeRFDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.dnerf_dataparser.DNeRF'>, data=PosixPath('data/dnerf/lego'), scale_factor=1.0, alpha_color='white'), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.phototourism_dataparser.PhototourismDataParserConfig, _SubcommandConfiguration(name='phototourism-data', default=PhototourismDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.phototourism_dataparser.Phototourism'>, data=PosixPath('data/phototourism/brandenburg-gate'), scale_factor=3.0, alpha_color='white', train_split_fraction=0.9, scene_scale=1.0, orientation_method='up', center_method='poses', auto_scale_poses=True), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.dycheck_dataparser.DycheckDataParserConfig, _SubcommandConfiguration(name='dycheck-data', default=DycheckDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.dycheck_dataparser.Dycheck'>, data=PosixPath('data/iphone/mochi-high-five'), scale_factor=5.0, alpha_color='white', downscale_factor=1, scene_box_bound=1.5), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.scannet_dataparser.ScanNetDataParserConfig, _SubcommandConfiguration(name='scannet-data', default=ScanNetDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.scannet_dataparser.ScanNet'>, data=PosixPath('data/scannet/scene0423_02'), scale_factor=1.0, scene_scale=1.0, center_method='poses', auto_scale_poses=True, train_split_fraction=0.9, depth_unit_scale_factor=0.001), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudioDataParserConfig, _SubcommandConfiguration(name='sdfstudio-data', default=SDFStudioDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudio'>, data=PosixPath('data/DTU/scan65'), include_mono_prior=False, depth_unit_scale_factor=0.001, include_foreground_mask=False, downscale_factor=1, scene_scale=2.0, skip_every_for_val_split=1, auto_orient=True), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSRDataParserConfig, _SubcommandConfiguration(name='nerfosr-data', default=NeRFOSRDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSR'>, data=PosixPath('data/NeRF-OSR/Data'), scene='stjacob', scene_scale=1.0, scale_factor=1.0, use_masks=False, orientation_method='vertical', center_method='focus', auto_scale_poses=True), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig, _SubcommandConfiguration(name='sitcoms3d-data', default=Sitcoms3DDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3D'>, data=PosixPath('data/sitcoms3d/TBBT-big_living_room'), include_semantics=True, downscale_factor=4, scene_scale=2.0), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.scannetpp_dataparser.ScanNetppDataParserConfig, _SubcommandConfiguration(name='scannetpp-data', default=ScanNetppDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.scannetpp_dataparser.ScanNetpp'>, data=PosixPath('scannetpp/410c470782'), scale_factor=1.0, scene_scale=1.5, orientation_method='up', center_method='poses', auto_scale_poses=True, images_dir=PosixPath('dslr/resized_images'), masks_dir=PosixPath('dslr/resized_anon_masks'), transforms_path=PosixPath('dslr/nerfstudio/transforms.json')), description='', prefix_name=False, constructor_factory=None)], typing.Annotated[nerfstudio.data.dataparsers.colmap_dataparser.ColmapDataParserConfig, _SubcommandConfiguration(name='colmap', default=ColmapDataParserConfig(_target=<class 'nerfstudio.data.dataparsers.colmap_dataparser.ColmapDataParser'>, data=PosixPath('.'), scale_factor=1.0, downscale_factor=None, scene_scale=1.0, orientation_method='up', center_method='poses', auto_scale_poses=True, assume_colmap_world_coordinate_convention=True, eval_mode='interval', train_split_fraction=0.9, eval_interval=8, depth_unit_scale_factor=0.001, images_path=PosixPath('images'), masks_path=None, depths_path=None, colmap_path=PosixPath('colmap/sparse/0'), load_3D_points=True, max_2D_matches_per_3D_point=0), description='', prefix_name=False, constructor_factory=None)]]. The types may also be too complex for tyro's subcommand matcher; support is particularly limited for custom generic types.

**Comment by SydneyWarrenZhao** [comment]
Thank you for your great work and decent replication

**Comment by jingwu2121** [comment]
Hi, can you go to this file `/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.10/site-packages/huggingface_hub/init.py` and there should be something like `from huggingface_hub import cached_download, hf_hub_download`. Please remove this `cached_download` and have another try. It works fine after removing this according to my experience.

**Comment by SydneyWarrenZhao** [comment]
Thank you apply. It works!
