### ISSUE TITLE
environment problem

### ISSUE THREAD

**Issue by SydneyWarrenZhao** [ActiveVisionLab/gaussctrl#19]

**Comment by SydneyWarrenZhao** [comment]
And can you update the installation instructions? There are some small errors in there. Thank you for your great work!

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nerfstudio 1.0.0 requires gsplat==0.1.2.1, but you have gsplat 0.1.3 which is incompatible.

**Comment by jingwu2121** [comment]
Hi there, what is the error message?
