### ISSUE TITLE
gsplat version error

### ISSUE THREAD

**Issue by WarrenZZZZL** [ActiveVisionLab/gaussctrl#26]
After I solve the error: RuntimeError: expected scalar type Float but found BFloat16

I change these variables all as float32:
            self.xys, depths, self.radii, conics, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
                means_crop.to(torch.float32),
                torch.exp(scales_crop).to(torch.float32),
                1,
                (quats_crop / quats_crop.norm(dim=-1, keepdim=True)).to(torch.float32),
                viewmat.squeeze()[:3, :].to(torch.float32),
                (projmat.squeeze() @ viewmat.squeeze()).to(torch.float32),
                camera.fx.item(),
                camera.fy.item(),
                cx,
                cy,
                H,
                W,
                tile_bounds,
            )  

And I use gsplat==0.1.2.1, nerfstudio==1.0.0, But this model still occurred this error:

Traceback (most recent call last):
  File "/home/lzha0538/miniconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.11/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.11/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.11/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.11/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/lzha0538/3Dediting/gaussctrl/gaussctrl/gc_trainer.py", line 76, in setup
    self.pipeline.render_reverse()
  File "/home/lzha0538/3Dediting/gaussctrl/gaussctrl/gc_pipeline.py", line 132, in render_reverse
    rendered_image = self._model.get_outputs_for_camera(current_cam)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzha0538/3Dediting/gaussctrl/gaussctrl/gc_model.py", line 271, in get_outputs_for_camera
    outs = self.get_outputs(camera.to(self.device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzha0538/3Dediting/gaussctrl/gaussctrl/gc_model.py", line 226, in get_outputs
    rgb, alpha = rasterize_gaussians(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: rasterize_gaussians() got an unexpected keyword argument 'return_alpha'

I just thought this is an error about gsplat error: so I changed the version of gsplat, but then I found all the versions are incompatible.

from versions: 0.0.1, 0.1.0,  0.1.1, ImportError: cannot import name 'project_gaussians' from 'gsplat.project_gaussians' 

 0.1.2.1TypeError: rasterize_gaussians() got an unexpected keyword argument 'return_alpha'
 , 0.1.3, 0.1.4   TypeError: 'str' object does not support item assignment
 
 , 0.1.5, ValueError: too many values to unpack (expected 6)
 0.1.6, 0.1.7, TypeError: '>' not supported between instances of 'tuple' and 'int'
  0.1.8,  0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13,AssertionError: block_width must be between 2 and 16
    
1.0.0, 1.1.0,1.1.1, 1.2.0, 1.3.0, 1.4.0ModuleNotFoundError: No module named 'gsplat._torch_impl'

**Comment by jingwu2121** [comment]
Hi, there, can you try version 0.1.3 `pip install gsplat==0.1.3`? See [here](https://github.com/ActiveVisionLab/gaussctrl/issues/22)

**Comment by WarrenZZZZL** [comment]
> Hi, there, can you try version 0.1.3 `pip install gsplat==0.1.3`? See [here](https://github.com/ActiveVisionLab/gaussctrl/issues/22)

It still doesn't work.

**Comment by dhsoon02** [comment]
Hi, I have met the same error.
**_"RuntimeError: expected scalar type Float but found BFloat16"_**

Did anyone solve the problem?
Thanks a lot!

**Comment by WarrenZ3** [comment]
> Hi, I have met the same error. **_"RuntimeError: expected scalar type Float but found BFloat16"_**
> 
> Did anyone solve the problem? Thanks a lot!

Actually, I tried this from the beginning. I don't know the reason, but it works.

**Comment by PotatoBigRoom** [comment]
So，I still don't know how to solve the problom,I tried to change the return of that founction,but I met lots of another ploblems
