### ISSUE TITLE
The pip error

### ISSUE THREAD

**Issue by yyhyyhyyhyyh** [ActiveVisionLab/gaussctrl#3]
Hi,nice work!
When I run this command:pip install -r requierment.txt
The error is:
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 2), huggingface-hub==0.20.3 and transformers because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested huggingface-hub==0.20.3
    diffusers 0.26.0 depends on huggingface-hub>=0.20.2
    transformers 4.34.1 depends on huggingface-hub<1.0 and >=0.16.4
    tokenizers 0.14.1 depends on huggingface_hub<0.18 and >=0.16.4
    The user requested huggingface-hub==0.20.3
    diffusers 0.26.0 depends on huggingface-hub>=0.20.2
    transformers 4.34.1 depends on huggingface-hub<1.0 and >=0.16.4
    tokenizers 0.14.0 depends on huggingface_hub<0.17 and >=0.16.4 

So do you know how to solve it?
Thank you very much!

**Comment by jingwu2121** [comment]
Hi there, can you please try this, and see if you can run it

```
transformers==4.44.2
diffusers==0.26.0
```
and do not specify the version of huggingface-hub

**Comment by yyhyyhyyhyyh** [comment]
Thank u!
It's ok
