### ISSUE TITLE
why your nerfstudio can rocognize gaussctrl?

### ISSUE THREAD

**Issue by massyzs** [ActiveVisionLab/gaussctrl#7]
In your command, you use "ns-train gaussctrl --load-checkpoint"
But ns-train in original repo does not support gaussctrl. Can you kindly teach me how you achieve this?

**Comment by jingwu2121** [comment]
hi there, you need to install this repo first, see here https://github.com/ActiveVisionLab/gaussctrl?tab=readme-ov-file#2-install-gaussctrl, then you will be able to use `ns-train gaussctrl`
