### ISSUE TITLE
How I can get the edited images?

### ISSUE THREAD

**Issue by weiyp0725** [ActiveVisionLab/gaussctrl#8]
Hi, thanks for your excellent work! I ran "ns-viewer --load-config {outputs/.../config.yml} " and get the edited 3D gs models,and how can I get the edited images 2D images?

**Comment by jingwu2121** [comment]
Hi, there, you need to render your images from your 3D model, see https://github.com/ActiveVisionLab/gaussctrl?tab=readme-ov-file#movie_camera-render-your-results

**Comment by ScienceLi1125** [comment]
Hi! I am confused about the editing results. Why is the new viewpoint rendered instead of the original dataset's viewpoint? What should I do if I want to render the original dataset's perspective?
