### ISSUE TITLE
Training a masked object

### ISSUE THREAD

**Issue by luoshuiyue** [ActiveVisionLab/gaussctrl#9]
Hi, how to training a masked object without background? how to train lego in NeRF blender dataset for example? thanks in advance

**Comment by jingwu2121** [comment]
Hi, please see [here](https://docs.nerf.studio/quickstart/existing_dataset.html), this dataset is built-in in the nerfstudio library

**Comment by luoshuiyue** [comment]
After check this, it works fine. How to use those type of mask (alpha channel) to replace lang-sam's mask in the second phase (ns-train gaussctrl)?

**Comment by jingwu2121** [comment]
Hi, there. please have a look at [this part](https://github.com/ActiveVisionLab/gaussctrl/blob/main/gaussctrl/gc_pipeline.py?plain=1#L144-L153). and replace the mask with your own ones

**Comment by luoshuiyue** [comment]
Okay, that's exactly my expectation under roughly glance, thank you for your great work!
